steps:
    - name: 'gcr.io/cloud-builders/docker'
      id: PyAppBuild
      args:
      - 'build'
      - '-t'
      - 'gcr.io/essential-truth-365415/pytradebyteapp:latest'
      - '.'

    - name: 'gcr.io/cloud-builders/docker'
      id: PyAppPush
      args:
      - 'push'
      - 'gcr.io/essential-truth-365415/pytradebyteapp:latest'

    - name: 'gcr.io/cloud-builders/gke-deploy'
      args:
        - run
        - --filename=k8s/
#        - --image=gcr.io/project-id/image:tag
        - --location=us-central1
        - --cluster=pyapp-cluster-1

images:
    - 'gcr.io/essential-truth-365415/pytradebyteapp:latest'
# End
