steps:
    - name: 'python:3.9-slim'
      id: UnitTest
      entrypoint: /bin/sh
      args:
      - '-c'
      - 'python tests/test.py'

    - name: 'gcr.io/cloud-builders/docker'
      id: PyAppBuild
      args:
      - 'build'
      - '-t'
      - 'gcr.io/essential-truth-365415/pytradebyteapp:latest'
      - '.'

    - name: 'gcr.io/cloud-builders/docker'
      id: PyAppPush
      args:
      - 'push'
      - 'gcr.io/essential-truth-365415/pytradebyteapp:latest'

    - name: 'gcr.io/cloud-builders/gke-deploy'
      args:
        - run
        - --filename=k8s/
#        - --image=gcr.io/project-id/image:tag
        - --location=us-east1-b
        - --cluster=py-cluster-1

images:
    - 'gcr.io/essential-truth-365415/pytradebyteapp:latest'
# End
