steps:
    - name: 'gcr.io/cloud-builders/docker'
      id: Build
      args:
      - 'build'
      - '-t'
      - 'gcr.io/essential-truth-365415/pytradebyteapp:$COMMIT_SHA'
      - '.'

    - name: 'gcr.io/cloud-builders/docker'
      id: Push
      args:
      - 'push'
      - 'gcr.io/essential-truth-365415/pytradebyteapp:$COMMIT_SHA'

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
      - 'run'
      - 'deploy'
      - 'pytradebyteapp'
      - '--image'
      - 'gcr.io/essential-truth-365415/pytradebyteapp:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--set-env-vars'
      - 'ENVIRONMENT=DEV'
      - 'HOST=localhost'
      - 'PORT=8000'
      - 'REDIS_HOST=localhost'
      - 'REDIS_PORT=6379'
      - 'REDIS_DB=0'

images:
    - 'gcr.io/essential-truth-365415/pytradebyteapp:$COMMIT_SHA'
# End
