apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: pyapp
deploy:
  kubectl:
    manifests:
      - k8s/py-app-deployment.yaml
      - k8s/py_app-service.yaml
      - k8s/redis-deployment.yaml
      - k8s/redis-service.yaml
      - k8s/dev-network-networkpolicy.yaml
